### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by apatlpo** [apatlpo/pistol#1]
- [ ] write equations of motions in [doc]

- [ ] write linear solver

- [ ] add nonlinear solver

- [ ] Consider time splitting
